img:
	docker-compose build

up:
	docker-compose --verbose up

reup:
	docker stop demo_project
	docker-compose --verbose build 
	docker-compose --verbose up 

stop:
	docker stop demo_project
